services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27777:27017"
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qwe

volumes:
  mongo-data:
